### PR TITLE
If bug is closed when updating, re-open it. 

### LINKED ISSUE #355: Reopen closed bugs in Bugzilla alert manager
If the function is updating a closed bug with new information, it should be reopened as part of the update

### PR DESCRIPTION
**Pull request by ajvb**
Fixes #355

### CODE REVIEW

File: contrib/common/bugzilla.go [hunk 1]
```diff
@@ -209,3 +210,42 @@ func (bc *BugzillaClient) SearchBugs(searchValues url.Values) (*SearchBugRespons
...
+	}
+
+	req, err := bc.CreateDefaultBugzillaRequest(http.MethodPut, fmt.Sprintf("%s/rest/bug/%d", bc.Url, bugId), bytes.NewReader(updateJson))
+	if err != nil {
+		log.Errorf("Error creating request: %s", err)
+		return err
+	}
+	req.Header.Add("Content-Type", "application/json")
+
+	resp, err := http.DefaultClient.Do(req)
```
Comment (ameihm0912) [inline contrib/common/bugzilla.go:233]: Are we missing a call to close `resp.Body` in this function?

Comment (ajvb) [reply contrib/common/bugzilla.go:236]: Yep, fixed.
